#  docker-compose -f docker-compose.yml config check validate config
# limweb/tlenswoole:v2
# limweb/trainer:v1

version: "3.5"
services:
  trainer:
    image: "limweb/trainer-nodegpu:v1"
    working_dir: /app/
    restart: always
    container_name: trainer
    command: "npx pm2-runtime start test3.js -n trainer -i 5"
    ports:
      - "8000:8000"
    labels:
      com.docker.compose.project: "trainer"
    networks:
      - faceml-backend

  facedb:
    image: "bitnami/mariadb:latest"
    container_name: facedb
    hostname: facedb
    restart: "always"
    ports:
      - "3309:3306"
    environment:
      TZ: Asia/Bangkok
      MARIADB_ROOT_PASSWORD: dbroot
      MARIADB_USER: dbuser
      MARIADB_PASSWORD: dbpass
      MARIADB_DATABASE: faces
      MARIADB_ROOT_HOST: "%"
    volumes:
      - faceml-data:/var/lib/mysql:rw
      - ./faces.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - faceml-backend

  faceml:
    image: "limweb/tlenswoole:v2"
    container_name: faceml
    working_dir: /app/
    restart: "always"
    ports:
      - "80:80"
    command: "/usr/local/bin/php /app/swooleserver.php"
    volumes:
      - ./:/app/
    labels:
      com.docker.compose.project: "faceml"
    depends_on:
      - "facedb"
    links:
      - "facedb"
    networks:
      - default
      - faceml-backend
volumes:
  faceml-data:

networks:
  default:
    driver: bridge
    external:
      name: faceml-frontend
  faceml-backend:
    external:
      name: faceml-backend
