#  docker-compose -f docker-compose.yml config check validate config
# limweb/tlenswoole:v2
# limweb/trainer:v1

version: "3.5"
services:
  # trainer:
  #   image: "limweb/trainer-nodegpu:v1"
  #   working_dir: /app/
  #   restart: always
  #   container_name: trainer
  #   command: "npx pm2-runtime start test3.js -n trainer -i 5"
  #   ports:
  #     - "8000:8000"
  #   labels:
  #     com.docker.compose.project: "trainer"
  #   networks:
  #     - faceml-backend

  facedb:
    image: "bitnami/mariadb:latest"
    container_name: facedb
    hostname: facedb
    restart: "always"
    ports:
      - "3309:3306"
    environment:
      TZ: Asia/Bangkok
      MARIADB_ROOT_PASSWORD: dbroot
      MARIADB_USER: dbuser
      MARIADB_PASSWORD: dbpass
      MARIADB_DATABASE: faces
      MARIADB_ROOT_HOST: "%"
    volumes:
      - faceml-data:/var/lib/mysql:rw
      - ./faces.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - faceml-backend

  redis:
    image: redis
    container_name: redis
    restart: "always"
    command: ["redis-server", "--appendonly", "yes"]
    expose:
      - 6379
    volumes:
      - redis-data:/data
    networks:
      - faceml-backend

  rabbitmq:
    image: "rabbitmq:3.8.1-beta.1-management"
    hostname: "rabbitmq"
    container_name: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    restart: "always"
    networks:
      - faceml-backend

  faceml:
    image: "limweb/tlenswoole:v3-rabbitmq"
    container_name: faceml
    working_dir: /app/
    restart: "always"
    # deploy:
    #   replicas: 3
    environment:
      - VIRTUAL_HOST: swoole.eventpass.co
    ports:
      - "8999:80"
    command: "/usr/local/bin/php /app/swooleserver.php"
    volumes:
      - ./:/app/
    labels:
      com.docker.compose.project: "faceml"
    depends_on:
      - "facedb"
      - "redis"
    links:
      - "facedb"
      - "redis"
      - "rabbitmq"
    networks:
      - default
      - faceml-backend

volumes:
  faceml-data:
  redis-data:

networks:
  default:
    driver: bridge
    external:
      name: faceml-frontend
  faceml-backend:
    external:
      name: faceml-backend
